# Generated by Django 4.2.7 on 2023-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_availability_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_date',
            field=models.DateField(),
        ),
    ]
