# Generated by Django 4.2.7 on 2023-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_availability_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage', max_digits=10),
        ),
    ]
