# Generated by Django 4.2.7 on 2023-12-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_reservation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the reservation has been paid for'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed'), (4, 'No Show'), (5, 'Payment Pending'), (6, 'Refunded'), (7, 'On Hold')], default=0),
        ),
    ]
