# Generated by Django 5.0.1 on 2024-01-31 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_chatmessage_chat_room_chatmessage_sender'),
        ('listings', '0005_alter_listing_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('listing', 'guest')},
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
        migrations.AlterModelTable(
            name='chatroom',
            table='chat_room',
        ),
    ]
