# Generated by Django 5.1 on 2024-11-14 20:49

import backend.listing.utils
import backend.main.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=backend.main.utils.UploadToPathAndRename('icons', 'name'))),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListingAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='If this is checked, the listing will be visible on the website.')),
            ],
            options={
                'verbose_name': 'Listing Analytics',
                'verbose_name_plural': 'Listing Analytics',
                'db_table': 'listing_analytics',
                'ordering': ['views', 'is_visible'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=backend.main.utils.UploadToPathAndRename('listing', 'listing.title'), validators=[backend.listing.utils.is_valid_image])),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'db_table': 'listing_image',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('content', models.JSONField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('price_details', models.JSONField(blank=True, null=True)),
                ('contact_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='address.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listing.category')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listing',
                'ordering': ['created_at', 'updated_at'],
            },
        ),
    ]
