# Generated by Django 5.1 on 2024-12-03 20:17

import backend.listing.utils
import backend.main.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=backend.main.utils.UploadToPathAndRename('listing', 'listing.name'), validators=[backend.listing.utils.is_valid_image]),
        ),
    ]
