# Generated by Django 4.2.7 on 2023-11-01 21:53

import backend.listings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.AddField(
            model_name='listing',
            name='house_addition',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(default='Emmen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(default=1234, max_length=10, validators=[backend.listings.utils.is_valid_dutch_zip_code]),
            preserve_default=False,
        ),
    ]
