# Generated by Django 4.2.7 on 2023-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_visible_alter_listing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='views',
            field=models.IntegerField(default=0, help_text='This is the number of times this listing has been viewed.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='visible',
            field=models.BooleanField(default=True, help_text='If this is checked, the listing will be visible on the website.'),
        ),
    ]
