# Generated by Django 5.0.1 on 2024-01-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_views_alter_listing_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='listings.address'),
        ),
    ]
