# Generated by Django 5.0.1 on 2024-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='enable_booking',
            field=models.BooleanField(default=True, help_text='If this is checked, the listing will have the "Booking" option available. (Uncheck this if users should contact you directly for the listing)'),
        ),
    ]
