# Generated by Django 5.1 on 2024-11-14 20:49

import backend.main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateField()),
                ('end_date_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availability',
                'ordering': ['start_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed'), (4, 'No Show'), (5, 'Payment Pending'), (6, 'Refunded'), (7, 'On Hold')], default=0)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=backend.main.utils.UploadToPathAndRename('reservation_comments', 'reservation.guest'))),
                ('status', models.SmallIntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation Comment',
                'verbose_name_plural': 'Reservation Comments',
                'db_table': 'reservation_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
