# Generated by Django 5.1 on 2024-11-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='listing.listing'),
        ),
    ]
