# Generated by Django 5.1 on 2024-11-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
    ]
