# Generated by Django 4.2.7 on 2023-11-14 13:47

import backend.listings.utils
import backend.main.utils
import backend.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='An non Dutch phone number must contain the country code with the "+" sign.', max_length=15, null=True, validators=[backend.users.utils.is_valid_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=backend.main.utils.UploadToPathAndRename('profile_pictures', 'user.first_name'), validators=[backend.listings.utils.is_valid_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='response_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='This is the percentage of messages replied to within 24 hours.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='response_time',
            field=models.DurationField(blank=True, help_text='This is the average time taken to reply to a message.', null=True),
        ),
    ]
